apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployer-tekton-tasks
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    directory:
      recurse: true
      exclude: '{**/*/catalog-info.yaml,**/*/tests/**}'
    repoURL: https://github.com/cloud-native-toolkit/deployer-tekton-tasks.git
    targetRevision: main
    path: tasks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
